apiVersion: v1
kind: Service
metadata:
  name: rewards-api
  labels:
    app: rewards-api
spec:
  type: ClusterIP
  selector:
    app: rewards-api
  ports:
    - name: http
      port: 8080
      targetPort: 8080
